### ISSUE TITLE
你好。服务端mac能跑起来吗？

### ISSUE THREAD

**Issue by jiaoxiaoyuan** [caojianyu/tauri-remote-desktop#1]

**Comment by jiaoxiaoyuan** [comment]
你好，mac环境服务端我跑起来了，客服端是需要打包吗？还是直接就可以用了？
<img width="1408" alt="image" src="https://user-images.githubusercontent.com/25316619/200303185-79d5efb7-7cc5-4508-b7fb-acde53d1b8b1.png">

**Comment by caojianyu** [comment]
服务端是交叉编译，如果在本地环境，可以直接运行。客户端需要运行两个，所以你最好还是打个运行程序，否则需要运行两个不同得客户端。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "caojianyu/tauri-remote-desktop"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月7日(星期一) 晚上7:50
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [caojianyu/tauri-remote-desktop] 你好。服务端mac能跑起来吗？ (Issue #1)





 
你好，mac环境服务端我跑起来了，客服端是需要打包吗？还是直接就可以用了？

**Comment by jiaoxiaoyuan** [comment]
你好，我还有一个小问题，就是rust的服务端是部署到云服务器比如腾讯云的centos7上？还是被远程和远程的电脑上都要装一个服务端？

**Comment by caojianyu** [comment]
服务端不管是在哪里部署，只需要部署一个，远程和被远程的客户端各需要一个客户端




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "caojianyu/tauri-remote-desktop"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月7日(星期一) 晚上9:35
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [caojianyu/tauri-remote-desktop] 你好。服务端mac能跑起来吗？ (Issue #1)





 
你好，我还有一个小问题，就是rust的服务端是部署到云服务器比如腾讯云的centos7上？还是被远程和远程的电脑上都要装一个服务端？
